name: rf-mut-f
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=3.6.1
  - r-randomforest
  - r-caret
  - r-e1071
  - r-catools
  - r-argparse
  - bcftools=1.10.2
  - tabix
